### PR TITLE
Evaluation criteria improvement 

### PR DESCRIPTION
**Pull request by wrenzi**
We made more clear what are our evaluation criteria as well as important instructions to develop the assignment. This README is being updated together with:

"Evaluation Criteria"
https://www.notion.so/myorign/Evaluation-Criteria-a6aa4b00b4e54737b0f44f7215e3c7c2

"Candidate Model"
https://www.notion.so/myorign/Candidate-Model-b36fdeaed0db413d8b51a3d9871521c6

### CODE REVIEW

**Comment by salesgu** [comment]
I approved, but I was thinking here. We can add another point: ask the candidate to not open a pull request here but create a repo at his own GitHub and send us a link (most of the people do this). What do you think?

**Comment by wrenzi** [comment]
> I approved, but I was thinking here. We can add another point: ask the candidate to not open a pull request here but create a repo at his own GitHub and send us a link (most of the people do this). What do you think?

hey @salesgu, it sounds good. 👍

**Comment by wrenzi** [comment]
@salesgu, there is already this delivery option for the candidate. Do you think you should use only one approach?

> Delivery Instructions
> We expect you to deliver your final code with one of these options:
> 
> You can open a Pull Request to this Github repository.
> You can send to us the link for your repository (make sure to make it public)

**Comment by salesgu** [comment]
> @salesgu, there is already this delivery option for the candidate. Do you think you should use only one approach?
> 
> > Delivery Instructions
> > We expect you to deliver your final code with one of these options:
> > You can open a Pull Request to this Github repository.
> > You can send to us the link for your repository (make sure to make it public)

Yes, in my opinion, it's better just send the link. Keep the things simple to all os us (origin and candidate)

**Comment by wrenzi** [comment]
Done @salesgu

**Comment by salesgu** [comment]
> Done @salesgu

Thanks!!

**Comment by wrenzi** [comment]
@matheuspoleza , @vagfsantos , @mariobrusarosco , I'll merge the pull request and your feedback will be welcome, indeed.

**Pull request merged**
